apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: devops13-deploy
        image: venugopalpotnuru/eks-project:spring-v3
        ports:
        - containerPort: 8080
